/* ═══════════════════════════════════════════════════════════════
   SchoolDocForge v6 — Document Renderers (generators.js)
   Pure HTML/CSS strings. No external dependencies at render time.
   v6 adds: transcript, visitor-badge, exam-paper, library-card,
            asset-tag, parent-notice, CA sheet, class-timetable,
            staff-id-card, inventory-report, library-overdue.
═══════════════════════════════════════════════════════════════ */
'use strict';

function renderDocument(type, p, f){
  p = p || {}; f = f || {};
  const wm = (window.getWatermark && window.getWatermark()) || null;
  const wmHTML = wm ? `<div style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center;pointer-events:none;z-index:1;"><div style="transform:rotate(-30deg);font-size:7rem;font-weight:900;color:${wm.color};opacity:${wm.opacity};letter-spacing:.1em;white-space:nowrap;">${esc(wm.text)}</div></div>` : '';
  const fn = RENDERERS[type] || RENDERERS.letterhead;
  const body = fn(p, f);
  return `<div class="doc-paper" style="position:relative;background:#fff;padding:40px 40px;min-height:1100px;width:794px;margin:0 auto;font-family:${p.docFont||'Georgia, serif'};color:#000;border:1px solid #ddd;box-shadow:0 4px 18px rgba(0,0,0,.08);">${wmHTML}<div style="position:relative;z-index:2;">${body}</div></div>`;
}
window.renderDocument = renderDocument;

function esc(s){ return (s==null?'':String(s)).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function lines(s){ return (s||'').split('\n').filter(Boolean); }
function n2w(n){ return (window.numberToWords ? window.numberToWords(n) : String(n)); }

/* ── Reusable header ── */
function header(p, opts={}){
  const logo = p.logo ? `<img src="${p.logo}" style="height:80px;width:80px;object-fit:contain;"/>` : `<div style="height:80px;width:80px;border:2px solid ${p.primaryColor||'#1a2e4a'};border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:2rem;font-weight:bold;color:${p.primaryColor||'#1a2e4a'};">${(p.name||'S').charAt(0)}</div>`;
  return `<div style="display:flex;gap:1rem;align-items:center;border-bottom:3px double ${p.primaryColor||'#1a2e4a'};padding-bottom:1rem;margin-bottom:1.5rem;">
    ${logo}
    <div style="flex:1;text-align:center;">
      <div style="font-size:1.9rem;font-weight:bold;color:${p.primaryColor||'#1a2e4a'};letter-spacing:.05em;">${esc((p.name||'SCHOOL NAME').toUpperCase())}</div>
      ${p.motto?`<div style="font-style:italic;color:${p.accentColor||'#c9921a'};margin-top:.2rem;font-size:.95rem;">"${esc(p.motto)}"</div>`:''}
      <div style="font-size:.85rem;color:#444;margin-top:.4rem;">${esc(p.address||'')}${p.city?', '+esc(p.city):''}${p.state?', '+esc(p.state)+' State':''}</div>
      <div style="font-size:.82rem;color:#444;margin-top:.2rem;">📞 ${esc(p.phone||'')}${p.phone2?' · '+esc(p.phone2):''}${p.email?' · ✉ '+esc(p.email):''}${p.website?' · 🌐 '+esc(p.website):''}</div>
      ${p.regNo?`<div style="font-size:.75rem;color:#666;margin-top:.2rem;">Reg: ${esc(p.regNo)}</div>`:''}
    </div>
  </div>`;
}
function footer(p){
  return `<div style="border-top:1px solid #999;margin-top:2rem;padding-top:.6rem;font-size:.72rem;color:#666;text-align:center;">${esc(p.name||'')} · ${esc(p.session||'')} ${esc(p.term||'')} · Generated by SchoolDocForge v6</div>`;
}

/* ═══════════════════════════════════════════════════════════════
   RENDERERS — one function per doc type
═══════════════════════════════════════════════════════════════ */
const RENDERERS = {
  letterhead(p,f){
    return header(p) + `
      <div style="margin-bottom:1rem;text-align:right;">${esc(f.date||new Date().toLocaleDateString())}</div>
      ${f.recipient?`<div style="margin-bottom:.8rem;">${esc(f.recipient)}</div>`:''}
      ${f.subject?`<div style="font-weight:bold;text-transform:uppercase;margin:.8rem 0;text-decoration:underline;">${esc(f.subject)}</div>`:''}
      <div style="white-space:pre-wrap;line-height:1.7;font-size:1rem;">${esc(f.body||'')}</div>
      <div style="margin-top:3rem;">
        <div style="border-top:1px solid #000;width:240px;padding-top:.3rem;">${esc(p.principal||'Principal')}</div>
        <div style="font-size:.85rem;color:#444;">Principal</div>
      </div>
    ` + footer(p);
  },
  certificate(p,f){
    const date = f.date || new Date().toLocaleDateString();
    return `<div style="border:8px double ${p.primaryColor||'#1a2e4a'};padding:2rem;text-align:center;min-height:900px;display:flex;flex-direction:column;justify-content:center;">
      ${p.logo?`<img src="${p.logo}" style="height:90px;margin:0 auto 1rem;"/>`:''}
      <div style="font-size:2.5rem;font-family:'Playfair Display',serif;color:${p.primaryColor||'#1a2e4a'};">${esc((p.name||'').toUpperCase())}</div>
      ${p.motto?`<div style="font-style:italic;color:${p.accentColor||'#c9921a'};">"${esc(p.motto)}"</div>`:''}
      <div style="font-size:2.6rem;font-family:'DM Serif Display',serif;margin:1.5rem 0 .5rem;color:${p.primaryColor||'#1a2e4a'};">Certificate of ${esc(f.certType||'Merit')}</div>
      <div style="font-size:1rem;color:#666;">This is to certify that</div>
      <div style="font-size:2.2rem;font-family:'Playfair Display',serif;font-style:italic;color:${p.accentColor||'#c9921a'};margin:1rem 0;">${esc(f.recipientName||'Recipient Name')}</div>
      <div style="font-size:1.05rem;max-width:600px;margin:0 auto;line-height:1.6;">${esc(f.awardDesc||'has demonstrated outstanding achievement and excellence.')}</div>
      <div style="display:flex;justify-content:space-around;margin-top:3.5rem;">
        <div><div style="border-top:1px solid #000;width:180px;padding-top:.3rem;">${esc(date)}</div><div style="font-size:.85rem;">Date</div></div>
        <div><div style="border-top:1px solid #000;width:180px;padding-top:.3rem;">${esc(p.principal||'Principal')}</div><div style="font-size:.85rem;">${esc(f.signatory||'Principal')}</div></div>
      </div>
      <div style="font-size:3rem;color:${p.accentColor||'#c9921a'};margin-top:1rem;">✦ ✦ ✦</div>
    </div>`;
  },
  banner(p,f){
    return `<div style="background:linear-gradient(135deg,${p.primaryColor||'#1a2e4a'},${p.accentColor||'#c9921a'});color:#fff;padding:3rem 2rem;text-align:center;min-height:1000px;display:flex;flex-direction:column;justify-content:center;">
      ${p.logo?`<img src="${p.logo}" style="height:100px;margin:0 auto 1rem;background:#fff;border-radius:50%;padding:.5rem;"/>`:''}
      <div style="font-size:1.5rem;letter-spacing:.2em;text-transform:uppercase;opacity:.85;">${esc((p.name||'').toUpperCase())}</div>
      <h1 style="font-size:4.5rem;margin:1.5rem 0 .5rem;font-family:'DM Serif Display',serif;">${esc(f.title||'EVENT TITLE')}</h1>
      <div style="font-size:1.8rem;opacity:.9;">${esc(f.subtitle||'')}</div>
      <div style="margin:2rem 0;font-size:1.4rem;">📅 ${esc(f.eventDate||'')} ${f.venue?' · 📍 ' + esc(f.venue):''}</div>
      <p style="font-size:1.1rem;max-width:600px;margin:1rem auto;line-height:1.6;white-space:pre-wrap;">${esc(f.details||'')}</p>
      <div style="margin-top:2rem;font-size:.95rem;opacity:.85;">${esc(p.phone||'')} · ${esc(p.email||'')}</div>
    </div>`;
  },
  'id-card'(p,f){
    const qrId = 'qr_' + Math.random().toString(36).slice(2);
    setTimeout(()=>{ const el = document.getElementById(qrId); if(el && window.QRCode){ el.innerHTML=''; new QRCode(el,{text: f.qrText || p.website || 'school', width:80, height:80}); } }, 30);
    return `<div style="width:340px;border:3px solid ${p.primaryColor||'#1a2e4a'};border-radius:12px;overflow:hidden;margin:1rem auto;background:#fff;">
      <div style="background:${p.primaryColor||'#1a2e4a'};color:#fff;padding:.8rem;text-align:center;">
        ${p.logo?`<img src="${p.logo}" style="height:40px;background:#fff;border-radius:50%;padding:.2rem;"/>`:''}
        <div style="font-size:.95rem;font-weight:bold;margin-top:.3rem;">${esc((p.name||'').toUpperCase())}</div>
        <div style="font-size:.7rem;opacity:.85;">${esc(p.address||'')}</div>
      </div>
      <div style="padding:1rem;display:flex;gap:1rem;">
        <div style="width:90px;height:110px;background:#eee;border:1px solid #ccc;display:flex;align-items:center;justify-content:center;font-size:2.5rem;">${esc((f.holderName||'?').charAt(0))}</div>
        <div style="flex:1;font-size:.8rem;">
          <div style="font-weight:bold;font-size:1rem;margin-bottom:.3rem;color:${p.primaryColor||'#1a2e4a'};">${esc(f.holderName||'Name')}</div>
          <div><strong>ID:</strong> ${esc(f.idNumber||'')}</div>
          <div><strong>Class:</strong> ${esc(f.holderClass||'')}</div>
          ${f.bloodGroup?`<div><strong>Blood:</strong> ${esc(f.bloodGroup)}</div>`:''}
          ${f.guardianPhone?`<div><strong>Phone:</strong> ${esc(f.guardianPhone)}</div>`:''}
        </div>
      </div>
      <div style="display:flex;justify-content:space-between;align-items:flex-end;padding:0 1rem .8rem;">
        <div style="font-size:.7rem;color:#666;">Session ${esc(p.session||'')}</div>
        <div id="${qrId}"></div>
      </div>
    </div>`;
  },
  'report-card'(p,f){
    const grade = m => m>=70?{g:'A',r:'Excellent'}:m>=60?{g:'B',r:'Very Good'}:m>=50?{g:'C',r:'Good'}:m>=45?{g:'D',r:'Pass'}:m>=40?{g:'E',r:'Fair'}:{g:'F',r:'Fail'};
    const subj = lines(f.subjects).map(l => { const [s,ca,ex] = l.split(','); const c=+ca||0, e=+ex||0, t=c+e; const G=grade(t); return { s:(s||'').trim(), ca:c, ex:e, t, g:G.g, r:G.r }; });
    const total = subj.reduce((a,b)=>a+b.t,0);
    const avg = subj.length ? (total/subj.length).toFixed(1) : 0;
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">STUDENT REPORT CARD — ${esc(p.session||'')} ${esc(p.term||'')}</h3>
      <table style="width:100%;margin:.5rem 0 1rem;font-size:.9rem;"><tr><td><strong>Name:</strong> ${esc(f.studentName||'')}</td><td><strong>Class:</strong> ${esc(f.studentClass||'')}</td><td><strong>Adm No:</strong> ${esc(f.admNo||'')}</td></tr></table>
      <table style="width:100%;border-collapse:collapse;font-size:.88rem;"><thead><tr style="background:${p.primaryColor||'#1a2e4a'};color:#fff;"><th style="padding:.4rem;border:1px solid #999;">Subject</th><th style="padding:.4rem;border:1px solid #999;">CA (40)</th><th style="padding:.4rem;border:1px solid #999;">Exam (60)</th><th style="padding:.4rem;border:1px solid #999;">Total</th><th style="padding:.4rem;border:1px solid #999;">Grade</th><th style="padding:.4rem;border:1px solid #999;">Remark</th></tr></thead><tbody>${subj.map(x=>`<tr><td style="padding:.35rem;border:1px solid #999;">${esc(x.s)}</td><td style="padding:.35rem;border:1px solid #999;text-align:center;">${x.ca}</td><td style="padding:.35rem;border:1px solid #999;text-align:center;">${x.ex}</td><td style="padding:.35rem;border:1px solid #999;text-align:center;"><strong>${x.t}</strong></td><td style="padding:.35rem;border:1px solid #999;text-align:center;font-weight:bold;color:${p.primaryColor||'#1a2e4a'};">${x.g}</td><td style="padding:.35rem;border:1px solid #999;">${x.r}</td></tr>`).join('')}<tr style="background:#f5f1ea;font-weight:bold;"><td colspan="3" style="padding:.4rem;border:1px solid #999;text-align:right;">Grand Total / Average:</td><td colspan="3" style="padding:.4rem;border:1px solid #999;">${total} &nbsp; (Avg ${avg})</td></tr></tbody></table>
      <div style="margin-top:1rem;font-size:.9rem;"><strong>Teacher's Remark:</strong> ${esc(f.teacherRemark||'')}</div>
      <div style="margin-top:.5rem;font-size:.9rem;"><strong>Principal's Remark:</strong> ${esc(f.principalRemark||'')}</div>
      <div style="display:flex;justify-content:space-between;margin-top:2.5rem;font-size:.85rem;"><div><div style="border-top:1px solid #000;width:180px;padding-top:.3rem;">${esc(p.principal||'')}</div>Principal</div><div><div style="border-top:1px solid #000;width:180px;padding-top:.3rem;">${esc(p.vicePrincipal||'')}</div>Vice-Principal</div></div>
      ` + footer(p);
  },
  'official-letter'(p,f){
    return header(p) + `
      <div style="text-align:right;margin-bottom:1rem;">${esc(f.date||new Date().toLocaleDateString())}</div>
      <div style="margin-bottom:.4rem;">${esc(f.recipient||'')}</div>
      <div style="white-space:pre-wrap;margin-bottom:1rem;font-size:.95rem;">${esc(f.address||'')}</div>
      ${f.subject?`<div style="font-weight:bold;text-transform:uppercase;text-decoration:underline;margin:.8rem 0;">Re: ${esc(f.subject)}</div>`:''}
      <div style="white-space:pre-wrap;line-height:1.7;">${esc(f.body||'')}</div>
      <div style="margin-top:3rem;"><div style="border-top:1px solid #000;width:240px;padding-top:.3rem;">${esc(f.signatory||p.principal||'')}</div><div style="font-size:.85rem;">${esc(f.signatoryTitle||'Principal')}</div></div>
    ` + footer(p);
  },
  'timetable'(p,f){
    const rows = lines(f.rows).map(l=>l.split(','));
    return header(p) + `<h3 style="text-align:center;">${esc(f.title||'EXAMINATION TIMETABLE')}</h3>
      <table style="width:100%;border-collapse:collapse;font-size:.9rem;margin-top:.5rem;"><thead><tr style="background:${p.primaryColor||'#1a2e4a'};color:#fff;"><th style="padding:.4rem;border:1px solid #999;">Subject</th><th style="padding:.4rem;border:1px solid #999;">Date</th><th style="padding:.4rem;border:1px solid #999;">Time</th><th style="padding:.4rem;border:1px solid #999;">Venue</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td style="padding:.35rem;border:1px solid #999;">${esc((c||'').trim())}</td>`).join('')}</tr>`).join('')}</tbody></table>
      ` + footer(p);
  },
  'admission-form'(p,f){
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">ADMISSION FORM — ${esc(f.session||p.session||'')}</h3>
      <div style="text-align:right;">Form No: ${esc(f.formNo||'')}</div>
      <table style="width:100%;font-size:.9rem;border-collapse:collapse;margin-top:1rem;">
        ${['Full Name','Date of Birth','Gender','Address','Parent/Guardian','Phone','Previous School','Class Applying For'].map(l=>`<tr><td style="padding:.5rem;border:1px solid #999;width:30%;background:#f5f1ea;font-weight:bold;">${l}</td><td style="padding:.5rem;border:1px solid #999;">&nbsp;</td></tr>`).join('')}
      </table>
      <div style="margin-top:1.5rem;font-size:.85rem;"><strong>Declaration:</strong> I hereby apply for admission and agree to the school's terms.</div>
      <div style="display:flex;justify-content:space-between;margin-top:2rem;"><div><div style="border-top:1px solid #000;width:180px;padding-top:.3rem;">Parent/Guardian</div></div><div><div style="border-top:1px solid #000;width:180px;padding-top:.3rem;">Date</div></div></div>
      ` + footer(p);
  },
  'fee-receipt'(p,f){
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">OFFICIAL FEE RECEIPT</h3>
      <table style="width:100%;font-size:.95rem;margin:1rem 0;"><tr><td><strong>Receipt No:</strong> ${esc(f.receiptNo||'R-'+Date.now())}</td><td style="text-align:right;"><strong>Date:</strong> ${esc(f.date||new Date().toLocaleDateString())}</td></tr></table>
      <table style="width:100%;border-collapse:collapse;font-size:.95rem;">
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;width:35%;">Received From</td><td style="padding:.5rem;border:1px solid #999;">${esc(f.studentName||'')}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Class</td><td style="padding:.5rem;border:1px solid #999;">${esc(f.studentClass||'')}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Purpose</td><td style="padding:.5rem;border:1px solid #999;">${esc(f.purpose||'')}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Method</td><td style="padding:.5rem;border:1px solid #999;">${esc(f.paymentMethod||'Cash')}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Amount</td><td style="padding:.5rem;border:1px solid #999;font-size:1.4rem;font-weight:bold;color:${p.primaryColor||'#1a2e4a'};">₦${(+f.amount||0).toLocaleString()}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">In Words</td><td style="padding:.5rem;border:1px solid #999;font-style:italic;">${esc(n2w(f.amount))} Naira Only</td></tr>
      </table>
      ${p.bankName?`<div style="margin-top:1rem;font-size:.85rem;background:#f9f7f2;padding:.6rem;border:1px dashed #ccc;"><strong>Bank Details:</strong> ${esc(p.bankName)} · ${esc(p.accountName||'')} · ${esc(p.accountNo||'')}</div>`:''}
      <div style="display:flex;justify-content:space-between;margin-top:2rem;font-size:.85rem;"><div><div style="border-top:1px solid #000;width:160px;padding-top:.3rem;">Cashier</div></div><div><div style="border-top:1px solid #000;width:160px;padding-top:.3rem;">${esc(p.principal||'Principal')}</div></div></div>
      ` + footer(p);
  },
  'newsletter'(p,f){
    return header(p) + `<h2 style="text-align:center;color:${p.primaryColor||'#1a2e4a'};">${esc(f.title||'School Newsletter')}</h2>
      <div style="text-align:center;color:#666;font-size:.85rem;margin-bottom:1rem;">${esc(f.edition||'')}</div>
      <div style="white-space:pre-wrap;line-height:1.8;column-count:2;column-gap:1.5rem;">${esc(f.body||'')}</div>
      ` + footer(p);
  },
  'permission-slip'(p,f){
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">PARENTAL PERMISSION SLIP</h3>
      <p>Dear Parent/Guardian,</p>
      <p>Your child is invited to participate in <strong>${esc(f.eventName||'')}</strong> on <strong>${esc(f.eventDate||'')}</strong> at <strong>${esc(f.venue||'')}</strong>.</p>
      <p style="white-space:pre-wrap;">${esc(f.details||'')}</p>
      <table style="width:100%;font-size:.9rem;margin-top:2rem;border-collapse:collapse;">
        <tr><td style="padding:.4rem;border:1px solid #999;">Student Name:</td><td style="padding:.4rem;border:1px solid #999;">&nbsp;</td></tr>
        <tr><td style="padding:.4rem;border:1px solid #999;">Class:</td><td style="padding:.4rem;border:1px solid #999;">&nbsp;</td></tr>
        <tr><td style="padding:.4rem;border:1px solid #999;">Parent Signature:</td><td style="padding:.4rem;border:1px solid #999;">&nbsp;</td></tr>
        <tr><td style="padding:.4rem;border:1px solid #999;">Date:</td><td style="padding:.4rem;border:1px solid #999;">&nbsp;</td></tr>
      </table>
      ` + footer(p);
  },
  'academic-calendar'(p,f){
    const events = lines(f.events).map(l=>l.split(','));
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">ACADEMIC CALENDAR — ${esc(f.session||p.session||'')}</h3>
      <table style="width:100%;border-collapse:collapse;font-size:.9rem;margin-top:1rem;"><thead><tr style="background:${p.primaryColor||'#1a2e4a'};color:#fff;"><th style="padding:.4rem;border:1px solid #999;">Date</th><th style="padding:.4rem;border:1px solid #999;">Event</th></tr></thead><tbody>${events.map(e=>`<tr><td style="padding:.4rem;border:1px solid #999;">${esc((e[0]||'').trim())}</td><td style="padding:.4rem;border:1px solid #999;">${esc((e[1]||'').trim())}</td></tr>`).join('')}</tbody></table>
      ` + footer(p);
  },
  'staff-payslip'(p,f){
    const b=+f.basic||0, a=+f.allowances||0, d=+f.deductions||0, net=b+a-d;
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">STAFF PAYSLIP — ${esc(f.period||'')}</h3>
      <table style="width:100%;font-size:.95rem;border-collapse:collapse;margin-top:1rem;">
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;width:35%;">Staff Name</td><td style="padding:.5rem;border:1px solid #999;">${esc(f.staffName||'')}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Staff ID</td><td style="padding:.5rem;border:1px solid #999;">${esc(f.staffId||'')}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Department</td><td style="padding:.5rem;border:1px solid #999;">${esc(f.dept||'')}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Basic Salary</td><td style="padding:.5rem;border:1px solid #999;">₦${b.toLocaleString()}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Allowances</td><td style="padding:.5rem;border:1px solid #999;">₦${a.toLocaleString()}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Deductions</td><td style="padding:.5rem;border:1px solid #999;">- ₦${d.toLocaleString()}</td></tr>
        <tr style="background:${p.primaryColor||'#1a2e4a'};color:#fff;"><td style="padding:.6rem;border:1px solid #999;"><strong>NET PAY</strong></td><td style="padding:.6rem;border:1px solid #999;font-size:1.3rem;"><strong>₦${net.toLocaleString()}</strong></td></tr>
      </table>
      <div style="margin-top:.6rem;font-style:italic;font-size:.85rem;">In words: ${esc(n2w(net))} Naira Only</div>
      <div style="display:flex;justify-content:space-between;margin-top:2.5rem;font-size:.85rem;"><div><div style="border-top:1px solid #000;width:160px;padding-top:.3rem;">Bursar</div></div><div><div style="border-top:1px solid #000;width:160px;padding-top:.3rem;">${esc(p.principal||'Principal')}</div></div></div>
      ` + footer(p);
  },
  'transfer-letter'(p,f){
    return header(p) + `<div style="text-align:right;">${esc(f.date||new Date().toLocaleDateString())}</div>
      <h3 style="text-align:center;text-decoration:underline;">TRANSFER CERTIFICATE / LEAVING CERTIFICATE</h3>
      <p>This is to certify that <strong>${esc(f.studentName||'')}</strong> (Adm. No: <strong>${esc(f.admNo||'')}</strong>) was a bona-fide student of this institution and has been duly granted permission to leave from <strong>${esc(f.classLeft||'')}</strong>.</p>
      <p style="white-space:pre-wrap;"><strong>Reason:</strong> ${esc(f.reason||'')}</p>
      <p>We wish ${esc(f.studentName||'the student')} continued success.</p>
      <div style="margin-top:2.5rem;"><div style="border-top:1px solid #000;width:240px;padding-top:.3rem;">${esc(p.principal||'')}</div><div style="font-size:.85rem;">Principal</div></div>
      ` + footer(p);
  },
  'lesson-note'(p,f){
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">LESSON NOTE</h3>
      <table style="width:100%;font-size:.9rem;margin-bottom:.6rem;"><tr><td><strong>Subject:</strong> ${esc(f.subject||'')}</td><td><strong>Class:</strong> ${esc(f.classLevel||'')}</td><td><strong>Date:</strong> ${esc(f.date||'')}</td></tr></table>
      <div style="margin-bottom:.6rem;"><strong>Topic:</strong> ${esc(f.topic||'')}</div>
      <div style="margin-bottom:.6rem;"><strong>Objectives:</strong><div style="white-space:pre-wrap;">${esc(f.objectives||'')}</div></div>
      <div style="margin-bottom:.6rem;"><strong>Materials:</strong> ${esc(f.materials||'')}</div>
      <div style="margin-bottom:.6rem;"><strong>Introduction:</strong><div style="white-space:pre-wrap;">${esc(f.intro||'')}</div></div>
      <div style="margin-bottom:.6rem;"><strong>Development:</strong><div style="white-space:pre-wrap;">${esc(f.development||'')}</div></div>
      <div style="margin-bottom:.6rem;"><strong>Conclusion:</strong><div style="white-space:pre-wrap;">${esc(f.conclusion||'')}</div></div>
      ` + footer(p);
  },
  'fee-voucher'(p,f){
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">FEE PAYMENT VOUCHER</h3>
      <table style="width:100%;font-size:.95rem;border-collapse:collapse;margin-top:1rem;">
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Student</td><td style="padding:.5rem;border:1px solid #999;">${esc(f.studentName||'')}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Class</td><td style="padding:.5rem;border:1px solid #999;">${esc(f.studentClass||'')}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Purpose</td><td style="padding:.5rem;border:1px solid #999;">${esc(f.purpose||'')}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Due Date</td><td style="padding:.5rem;border:1px solid #999;">${esc(f.dueDate||'')}</td></tr>
        <tr><td style="padding:.5rem;border:1px solid #999;background:#f5f1ea;">Amount Due</td><td style="padding:.5rem;border:1px solid #999;font-size:1.3rem;color:${p.primaryColor||'#1a2e4a'};"><strong>₦${(+f.amount||0).toLocaleString()}</strong></td></tr>
      </table>
      ${p.bankName?`<div style="margin-top:1rem;background:#f9f7f2;padding:.6rem;border:1px dashed #ccc;font-size:.85rem;"><strong>Pay Into:</strong> ${esc(p.bankName)} · ${esc(p.accountName||'')} · ${esc(p.accountNo||'')}</div>`:''}
      ` + footer(p);
  },
  'suspension-letter'(p,f){
    return header(p) + `<div style="text-align:right;">${esc(new Date().toLocaleDateString())}</div>
      <h3 style="text-align:center;text-decoration:underline;color:#b91c1c;">LETTER OF SUSPENSION</h3>
      <p>Dear Parent/Guardian,</p>
      <p>This is to inform you that your ward <strong>${esc(f.studentName||'')}</strong> (Adm. No: <strong>${esc(f.admNo||'')}</strong>) of <strong>${esc(f.classLevel||'')}</strong> has been suspended from school for <strong>${esc(f.days||'')}</strong> days effective <strong>${esc(f.startDate||'')}</strong>.</p>
      <p><strong>Offence:</strong> <span style="white-space:pre-wrap;">${esc(f.offence||'')}</span></p>
      <p>Kindly come to the school for a meeting before resumption.</p>
      <div style="margin-top:2.5rem;"><div style="border-top:1px solid #000;width:240px;padding-top:.3rem;">${esc(p.principal||'')}</div><div style="font-size:.85rem;">Principal</div></div>
      ` + footer(p);
  },
  'clearance-form'(p,f){
    const depts = ['Bursary','Library','Sports','Hostel','Subject Teacher','Form Master','Vice-Principal','Principal'];
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">SCHOOL CLEARANCE FORM</h3>
      <table style="width:100%;font-size:.9rem;margin:.5rem 0 1rem;"><tr><td><strong>Name:</strong> ${esc(f.studentName||'')}</td><td><strong>Adm No:</strong> ${esc(f.admNo||'')}</td><td><strong>Class:</strong> ${esc(f.classLevel||'')}</td><td><strong>Date:</strong> ${esc(f.date||'')}</td></tr></table>
      <table style="width:100%;border-collapse:collapse;font-size:.9rem;"><thead><tr style="background:${p.primaryColor||'#1a2e4a'};color:#fff;"><th style="padding:.4rem;border:1px solid #999;">Department</th><th style="padding:.4rem;border:1px solid #999;">Status</th><th style="padding:.4rem;border:1px solid #999;">Signature</th><th style="padding:.4rem;border:1px solid #999;">Date</th></tr></thead><tbody>${depts.map(d=>`<tr><td style="padding:.4rem;border:1px solid #999;">${esc(d)}</td><td style="padding:.4rem;border:1px solid #999;">&nbsp;</td><td style="padding:.4rem;border:1px solid #999;">&nbsp;</td><td style="padding:.4rem;border:1px solid #999;">&nbsp;</td></tr>`).join('')}</tbody></table>
      ` + footer(p);
  },

  /* ── v6 NEW ── */
  'transcript'(p,f){
    const rows = lines(f.terms).map(l => { const [term, subj, sc] = l.split(','); return { term:(term||'').trim(), subj:(subj||'').trim(), sc:+sc||0 }; });
    const terms = {};
    rows.forEach(r => { if(!terms[r.term]) terms[r.term]=[]; terms[r.term].push(r); });
    const tBlocks = Object.keys(terms).map(t => {
      const tot = terms[t].reduce((a,b)=>a+b.sc,0); const avg = (tot/terms[t].length).toFixed(1);
      return `<div style="margin-top:.8rem;"><strong>${esc(t)}</strong><table style="width:100%;border-collapse:collapse;font-size:.85rem;margin-top:.3rem;"><thead><tr style="background:#eee;"><th style="padding:.3rem;border:1px solid #999;">Subject</th><th style="padding:.3rem;border:1px solid #999;">Score</th></tr></thead><tbody>${terms[t].map(r=>`<tr><td style="padding:.3rem;border:1px solid #999;">${esc(r.subj)}</td><td style="padding:.3rem;border:1px solid #999;text-align:center;">${r.sc}</td></tr>`).join('')}<tr style="font-weight:bold;background:#fafafa;"><td style="padding:.3rem;border:1px solid #999;">Total / Avg</td><td style="padding:.3rem;border:1px solid #999;text-align:center;">${tot} (${avg})</td></tr></tbody></table></div>`;
    }).join('');
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">CUMULATIVE ACADEMIC TRANSCRIPT</h3>
      <table style="width:100%;font-size:.9rem;margin:.5rem 0;"><tr><td><strong>Name:</strong> ${esc(f.studentName||'')}</td><td><strong>Adm No:</strong> ${esc(f.admNo||'')}</td></tr></table>
      ${tBlocks || '<p style="color:#888;">No term data entered.</p>'}
      <div style="margin-top:2rem;"><div style="border-top:1px solid #000;width:240px;padding-top:.3rem;">${esc(p.principal||'Principal')}</div><div style="font-size:.85rem;">Principal</div></div>
      ` + footer(p);
  },
  'visitor-badge'(p,f){
    return `<div class="visitor-badge" style="width:340px;margin:1rem auto;border:2px solid ${p.primaryColor||'#1a2e4a'};padding:1rem;text-align:center;background:#fff;">
      ${p.logo?`<img src="${p.logo}" style="height:46px;"/>`:''}
      <div class="vb-school" style="font-size:1.05rem;font-weight:bold;color:${p.primaryColor||'#1a2e4a'};">${esc((p.name||'').toUpperCase())}</div>
      <div style="background:${p.accentColor||'#c9921a'};color:#fff;font-weight:bold;letter-spacing:.15em;padding:.3rem;margin:.5rem 0;">VISITOR</div>
      <div class="vb-photo" style="width:90px;height:90px;background:#eee;border-radius:50%;margin:.6rem auto;display:flex;align-items:center;justify-content:center;font-size:2.2rem;">${esc((f.photo||f.visitorName||'V').charAt(0).toUpperCase())}</div>
      <div style="font-size:1.1rem;font-weight:bold;">${esc(f.visitorName||'')}</div>
      <div style="font-size:.85rem;color:#444;">Visiting: ${esc(f.visiting||'')}</div>
      <div style="font-size:.85rem;color:#444;">Purpose: ${esc(f.purpose||'')}</div>
      <div style="font-size:.78rem;color:#666;margin-top:.5rem;">${esc(f.date||new Date().toLocaleDateString())}</div>
      <div style="margin-top:.6rem;font-size:.7rem;color:#888;">Return badge at exit · ${esc(p.phone||'')}</div>
    </div>`;
  },
  'exam-paper'(p,f){
    const qs = lines(f.questions);
    return header(p) + `<h2 style="text-align:center;">${esc(f.title||'Examination Paper')}</h2>
      <table style="width:100%;font-size:.9rem;margin-bottom:1rem;"><tr><td><strong>Subject:</strong> ${esc(f.subject||'')}</td><td><strong>Class:</strong> ${esc(f.classLevel||'')}</td><td><strong>Duration:</strong> ${esc(f.duration||'')} mins</td></tr></table>
      <div style="border:1px solid #999;padding:.5rem;background:#fafafa;font-size:.88rem;white-space:pre-wrap;"><strong>Instructions:</strong> ${esc(f.instructions||'Answer ALL questions.')}</div>
      <ol style="margin-top:1rem;line-height:1.7;">${qs.map(q=>`<li style="margin-bottom:.4rem;">${esc(q)}</li>`).join('')}</ol>
      <div style="margin-top:2rem;text-align:center;font-style:italic;">— END OF PAPER —</div>
      ` + footer(p);
  },
  'library-card'(p,f){
    const qrId = 'qr_'+Math.random().toString(36).slice(2);
    setTimeout(()=>{ const el=document.getElementById(qrId); if(el && window.QRCode){ el.innerHTML=''; new QRCode(el,{text:f.cardNo||'lib',width:70,height:70}); } },30);
    return `<div style="width:340px;border:2px solid ${p.primaryColor||'#1a2e4a'};border-radius:10px;padding:1rem;margin:1rem auto;background:#fff;">
      <div style="text-align:center;font-weight:bold;color:${p.primaryColor||'#1a2e4a'};">${esc((p.name||'').toUpperCase())}</div>
      <div style="text-align:center;background:${p.accentColor||'#c9921a'};color:#fff;padding:.25rem;margin:.4rem 0;font-weight:bold;">LIBRARY CARD</div>
      <div><strong>Name:</strong> ${esc(f.borrowerName||'')}</div>
      <div><strong>Class/Dept:</strong> ${esc(f.borrowerClass||'')}</div>
      <div><strong>Card No:</strong> ${esc(f.cardNo||'')}</div>
      <div><strong>Valid Until:</strong> ${esc(f.validUntil||'')}</div>
      <div style="display:flex;justify-content:flex-end;margin-top:.5rem;"><div id="${qrId}"></div></div>
    </div>`;
  },
  'asset-tag'(p,f){
    const qrId='qr_'+Math.random().toString(36).slice(2);
    setTimeout(()=>{ const el=document.getElementById(qrId); if(el && window.QRCode){ el.innerHTML=''; new QRCode(el,{text:f.tagNo||'asset',width:90,height:90}); } },30);
    return `<div style="width:280px;border:2px dashed ${p.primaryColor||'#1a2e4a'};padding:1rem;margin:1rem auto;background:#fff;text-align:center;">
      <div style="font-weight:bold;color:${p.primaryColor||'#1a2e4a'};">${esc((p.name||'').toUpperCase())}</div>
      <div style="background:${p.accentColor||'#c9921a'};color:#fff;padding:.3rem;font-weight:bold;letter-spacing:.1em;margin:.5rem 0;">ASSET</div>
      <div style="font-size:1.05rem;font-weight:bold;">${esc(f.assetName||'')}</div>
      <div style="font-family:monospace;margin:.4rem 0;">${esc(f.tagNo||'')}</div>
      <div style="font-size:.8rem;">Custodian: ${esc(f.custodian||'')}</div>
      <div style="font-size:.8rem;">Acquired: ${esc(f.acquired||'')}</div>
      <div id="${qrId}" style="display:flex;justify-content:center;margin-top:.6rem;"></div>
    </div>`;
  },
  'parent-notice'(p,f){
    const colour = f.type==='Suspension'?'#b91c1c': f.type==='Caution'?'#b45309' : f.type==='Merit'||f.type==='Achievement'?'#15803d' : (p.primaryColor||'#1a2e4a');
    return header(p) + `<div style="text-align:right;">${esc(f.date||new Date().toLocaleDateString())}</div>
      <h3 style="text-align:center;color:${colour};text-decoration:underline;">PARENT NOTICE — ${esc((f.type||'NOTICE').toUpperCase())}</h3>
      <p>Dear Parent/Guardian of <strong>${esc(f.studentName||'')}</strong> (<strong>${esc(f.classLevel||'')}</strong>),</p>
      <div style="white-space:pre-wrap;line-height:1.7;border-left:4px solid ${colour};padding-left:.8rem;">${esc(f.body||'')}</div>
      <p style="margin-top:1rem;">Kindly acknowledge by signing below.</p>
      <div style="display:flex;justify-content:space-between;margin-top:2rem;font-size:.85rem;"><div><div style="border-top:1px solid #000;width:160px;padding-top:.3rem;">Parent</div></div><div><div style="border-top:1px solid #000;width:160px;padding-top:.3rem;">${esc(p.principal||'Principal')}</div></div></div>
      ` + footer(p);
  },
  'continuous-assessment'(p,f){
    const rows = lines(f.rows).map(l => l.split(',').map(c=>(c||'').trim()));
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">CONTINUOUS ASSESSMENT — ${esc(f.subject||'')} · ${esc(f.studentClass||'')}</h3>
      <table style="width:100%;border-collapse:collapse;font-size:.85rem;margin-top:.5rem;"><thead><tr style="background:${p.primaryColor||'#1a2e4a'};color:#fff;"><th style="padding:.35rem;border:1px solid #999;">#</th><th style="padding:.35rem;border:1px solid #999;">Name</th><th style="padding:.35rem;border:1px solid #999;">Test 1</th><th style="padding:.35rem;border:1px solid #999;">Test 2</th><th style="padding:.35rem;border:1px solid #999;">Assign</th><th style="padding:.35rem;border:1px solid #999;">Project</th><th style="padding:.35rem;border:1px solid #999;">Total/40</th></tr></thead><tbody>${rows.map((r,i)=>{ const tot = r.slice(1,5).reduce((a,b)=>a+(+b||0),0); return `<tr><td style="padding:.3rem;border:1px solid #999;text-align:center;">${i+1}</td><td style="padding:.3rem;border:1px solid #999;">${esc(r[0]||'')}</td><td style="padding:.3rem;border:1px solid #999;text-align:center;">${esc(r[1]||'')}</td><td style="padding:.3rem;border:1px solid #999;text-align:center;">${esc(r[2]||'')}</td><td style="padding:.3rem;border:1px solid #999;text-align:center;">${esc(r[3]||'')}</td><td style="padding:.3rem;border:1px solid #999;text-align:center;">${esc(r[4]||'')}</td><td style="padding:.3rem;border:1px solid #999;text-align:center;font-weight:bold;">${tot}</td></tr>`; }).join('')}</tbody></table>
      ` + footer(p);
  },
  'class-timetable'(p,f){
    const rows = lines(f.rows).map(l=>l.split(','));
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">CLASS TIMETABLE — ${esc(f.classLevel||'')}</h3>
      <table style="width:100%;border-collapse:collapse;font-size:.85rem;margin-top:.5rem;"><thead><tr style="background:${p.primaryColor||'#1a2e4a'};color:#fff;"><th style="padding:.35rem;border:1px solid #999;">Day</th><th style="padding:.35rem;border:1px solid #999;">Period</th><th style="padding:.35rem;border:1px solid #999;">Subject</th><th style="padding:.35rem;border:1px solid #999;">Teacher</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td style="padding:.3rem;border:1px solid #999;">${esc((c||'').trim())}</td>`).join('')}</tr>`).join('')}</tbody></table>
      ` + footer(p);
  },
  'staff-id-card'(p,f){
    const qrId='qr_'+Math.random().toString(36).slice(2);
    setTimeout(()=>{ const el=document.getElementById(qrId); if(el && window.QRCode){ el.innerHTML=''; new QRCode(el,{text:f.qrText||p.website||'staff',width:80,height:80}); } },30);
    return `<div style="width:340px;border:3px solid ${p.accentColor||'#c9921a'};border-radius:12px;overflow:hidden;margin:1rem auto;background:#fff;">
      <div style="background:${p.accentColor||'#c9921a'};color:#000;padding:.8rem;text-align:center;">
        ${p.logo?`<img src="${p.logo}" style="height:40px;background:#fff;border-radius:50%;padding:.2rem;"/>`:''}
        <div style="font-size:.95rem;font-weight:bold;margin-top:.3rem;">${esc((p.name||'').toUpperCase())}</div>
        <div style="font-size:.7rem;">STAFF</div>
      </div>
      <div style="padding:1rem;display:flex;gap:1rem;">
        <div style="width:90px;height:110px;background:#eee;border:1px solid #ccc;display:flex;align-items:center;justify-content:center;font-size:2.5rem;">${esc((f.holderName||'?').charAt(0))}</div>
        <div style="flex:1;font-size:.8rem;">
          <div style="font-weight:bold;font-size:1rem;margin-bottom:.3rem;color:${p.primaryColor||'#1a2e4a'};">${esc(f.holderName||'Name')}</div>
          <div><strong>ID:</strong> ${esc(f.idNumber||'')}</div>
          <div><strong>Dept:</strong> ${esc(f.holderClass||'')}</div>
          ${f.bloodGroup?`<div><strong>Blood:</strong> ${esc(f.bloodGroup)}</div>`:''}
          ${f.guardianPhone?`<div><strong>NoK:</strong> ${esc(f.guardianPhone)}</div>`:''}
        </div>
      </div>
      <div style="display:flex;justify-content:space-between;align-items:flex-end;padding:0 1rem .8rem;">
        <div style="font-size:.7rem;color:#666;">Session ${esc(p.session||'')}</div>
        <div id="${qrId}"></div>
      </div>
    </div>`;
  },
  'inventory-report'(p,f){
    const assets = (window.lsGet ? window.lsGet('assets',[]) : []);
    const total = assets.reduce((a,b)=>a+(+b.cost||0),0);
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">${esc(f.title||'INVENTORY / ASSET REPORT')} — ${esc(f.period||'')}</h3>
      <p>${esc(f.summary||'')}</p>
      <table style="width:100%;border-collapse:collapse;font-size:.82rem;margin-top:1rem;"><thead><tr style="background:${p.primaryColor||'#1a2e4a'};color:#fff;"><th style="padding:.35rem;border:1px solid #999;">#</th><th style="padding:.35rem;border:1px solid #999;">Asset</th><th style="padding:.35rem;border:1px solid #999;">Tag</th><th style="padding:.35rem;border:1px solid #999;">Category</th><th style="padding:.35rem;border:1px solid #999;">Custodian</th><th style="padding:.35rem;border:1px solid #999;">Acquired</th><th style="padding:.35rem;border:1px solid #999;">Cost</th><th style="padding:.35rem;border:1px solid #999;">Condition</th></tr></thead><tbody>${assets.map((a,i)=>`<tr><td style="padding:.3rem;border:1px solid #999;text-align:center;">${i+1}</td><td style="padding:.3rem;border:1px solid #999;">${esc(a.name||'')}</td><td style="padding:.3rem;border:1px solid #999;">${esc(a.tag||'')}</td><td style="padding:.3rem;border:1px solid #999;">${esc(a.cat||'')}</td><td style="padding:.3rem;border:1px solid #999;">${esc(a.custodian||'')}</td><td style="padding:.3rem;border:1px solid #999;">${esc(a.acquired||'')}</td><td style="padding:.3rem;border:1px solid #999;">₦${(+a.cost||0).toLocaleString()}</td><td style="padding:.3rem;border:1px solid #999;">${esc(a.condition||'')}</td></tr>`).join('')}<tr style="background:#f5f1ea;font-weight:bold;"><td colspan="6" style="padding:.4rem;border:1px solid #999;text-align:right;">TOTAL ASSET VALUE</td><td colspan="2" style="padding:.4rem;border:1px solid #999;">₦${total.toLocaleString()}</td></tr></tbody></table>
      ` + footer(p);
  },
  'library-overdue'(p,f){
    return header(p) + `<div style="text-align:right;">${esc(new Date().toLocaleDateString())}</div>
      <h3 style="text-align:center;text-decoration:underline;color:#b91c1c;">LIBRARY OVERDUE NOTICE</h3>
      <p>Dear <strong>${esc(f.borrowerName||'')}</strong>,</p>
      <p>Our records show that the book <strong>"${esc(f.bookTitle||'')}"</strong> is overdue by <strong>${esc(f.daysOverdue||'')}</strong> day(s).</p>
      <p>A fine of <strong>₦${(+f.fine||0).toLocaleString()}</strong> has accrued. Kindly return the book and settle the fine at the library.</p>
      <div style="margin-top:2rem;"><div style="border-top:1px solid #000;width:240px;padding-top:.3rem;">Librarian</div></div>
      ` + footer(p);
  }
};
window.RENDERERS = RENDERERS;

/* ═══════════════════════════════════════════════════════════════
   v7 ADDITIONAL RENDERERS — appended without removing originals
═══════════════════════════════════════════════════════════════ */
Object.assign(RENDERERS, {
  'soap-note'(p, f){
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">CLINIC / SOAP NOTE</h3>
      <table style="width:100%;font-size:.9rem;margin:.6rem 0;"><tr><td><strong>Patient:</strong> ${esc(f.studentName||'')}</td><td><strong>Date:</strong> ${esc(f.date||'')}</td><td><strong>Temp:</strong> ${esc(f.temp||'-')}°C · <strong>BP:</strong> ${esc(f.bp||'-')}</td></tr></table>
      <div style="border:1px solid #999;padding:.7rem;margin-bottom:.5rem;"><strong>S — Subjective (complaint):</strong><div style="white-space:pre-wrap;margin-top:.3rem;">${esc(f.subjective||'')}</div></div>
      <div style="border:1px solid #999;padding:.7rem;margin-bottom:.5rem;"><strong>O — Objective (findings):</strong><div style="white-space:pre-wrap;margin-top:.3rem;">${esc(f.objective||'')}</div></div>
      <div style="border:1px solid #999;padding:.7rem;margin-bottom:.5rem;"><strong>A — Assessment (diagnosis):</strong><div style="white-space:pre-wrap;margin-top:.3rem;">${esc(f.assessment||'')}</div></div>
      <div style="border:1px solid #999;padding:.7rem;margin-bottom:.5rem;"><strong>P — Plan / Treatment:</strong><div style="white-space:pre-wrap;margin-top:.3rem;">${esc(f.plan||'')}</div></div>
      <div style="margin-top:1.5rem;"><div style="border-top:1px solid #000;width:240px;padding-top:.3rem;">${esc(f.nurse||'Nurse / School Officer')}</div></div>
    ` + footer(p);
  },
  'transport-pass'(p, f){
    const qrId = 'qr_'+Math.random().toString(36).slice(2);
    setTimeout(()=>{ const el=document.getElementById(qrId); if(el && window.QRCode){ el.innerHTML=''; new QRCode(el,{text:f.plate||'bus',width:80,height:80}); } },30);
    return `<div style="width:340px;border:2px solid ${p.primaryColor||'#1a2e4a'};border-radius:10px;padding:1rem;margin:1rem auto;background:#fff;">
      <div style="text-align:center;font-weight:bold;color:${p.primaryColor||'#1a2e4a'};">${esc((p.name||'').toUpperCase())}</div>
      <div style="text-align:center;background:#10b981;color:#fff;padding:.3rem;margin:.5rem 0;font-weight:bold;letter-spacing:.1em;">🚌 BUS PASS</div>
      <div><strong>Bus:</strong> ${esc(f.plate||'')}</div>
      <div><strong>Route:</strong> ${esc(f.route||'')}</div>
      <div><strong>Driver:</strong> ${esc(f.driver||'')}</div>
      <div><strong>Valid Until:</strong> ${esc(f.validUntil||'')}</div>
      <div style="display:flex;justify-content:flex-end;margin-top:.5rem;"><div id="${qrId}"></div></div>
    </div>`;
  },
  'transport-roster'(p, f){
    const lines = (f.students||'').split('\n').filter(Boolean).map(l => l.split(','));
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">DAILY BUS ROSTER</h3>
      <table style="width:100%;font-size:.9rem;"><tr><td><strong>Bus:</strong> ${esc(f.plate||'')}</td><td><strong>Route:</strong> ${esc(f.route||'')}</td><td><strong>Driver:</strong> ${esc(f.driver||'')}</td><td><strong>Date:</strong> ${esc(f.date||'')}</td></tr></table>
      <table style="width:100%;border-collapse:collapse;font-size:.88rem;margin-top:1rem;"><thead><tr style="background:${p.primaryColor||'#1a2e4a'};color:#fff;"><th style="padding:.3rem;border:1px solid #999;">#</th><th style="padding:.3rem;border:1px solid #999;">Student</th><th style="padding:.3rem;border:1px solid #999;">Class</th><th style="padding:.3rem;border:1px solid #999;">Guardian Phone</th><th style="padding:.3rem;border:1px solid #999;">Boarded</th><th style="padding:.3rem;border:1px solid #999;">Dropped</th></tr></thead><tbody>${lines.map((r,i)=>`<tr><td style="padding:.3rem;border:1px solid #999;text-align:center;">${i+1}</td><td style="padding:.3rem;border:1px solid #999;">${esc((r[0]||'').trim())}</td><td style="padding:.3rem;border:1px solid #999;">${esc((r[1]||'').trim())}</td><td style="padding:.3rem;border:1px solid #999;">${esc((r[2]||'').trim())}</td><td style="padding:.3rem;border:1px solid #999;">&nbsp;</td><td style="padding:.3rem;border:1px solid #999;">&nbsp;</td></tr>`).join('')}</tbody></table>
      <div style="margin-top:1.5rem;"><div style="border-top:1px solid #000;width:240px;padding-top:.3rem;">Driver Signature / Date</div></div>
      ` + footer(p);
  },
  'cafe-menu'(p, f){
    const days = (f.meals||'').split('\n').filter(Boolean);
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">CAFETERIA MENU — ${esc(f.week||'This Week')}</h3>
      ${days.map(d => { const [day, meals] = d.split('::'); return `<div style="border:1px solid #999;margin-top:.5rem;padding:.6rem;"><strong style="color:${p.primaryColor||'#1a2e4a'};">${esc((day||'').trim())}</strong><div style="margin-top:.3rem;font-size:.9rem;">${esc((meals||'').trim())}</div></div>`; }).join('')}
      <div style="margin-top:1rem;font-size:.8rem;color:#666;font-style:italic;">Allergens & dietary substitutions available on request — please notify the kitchen 24 hours ahead.</div>
      ` + footer(p);
  },
  'meal-ticket'(p, f){
    return `<div style="width:280px;border:2px dashed ${p.primaryColor||'#1a2e4a'};padding:.8rem;margin:1rem auto;background:#fff;text-align:center;">
      <div style="font-weight:bold;color:${p.primaryColor||'#1a2e4a'};font-size:.95rem;">${esc((p.name||'').toUpperCase())}</div>
      <div style="background:${p.accentColor||'#c9921a'};color:#000;padding:.3rem;font-weight:bold;letter-spacing:.15em;margin:.5rem 0;">🍱 MEAL TICKET</div>
      <div style="font-size:1.05rem;font-weight:bold;">${esc(f.studentName||'')}</div>
      <div style="font-size:.85rem;">Class: ${esc(f.classLevel||'')}</div>
      <div style="font-size:.85rem;">${esc(f.mealType||'Lunch')} · ${esc(f.date||'')}</div>
      <div style="font-size:.7rem;color:#888;margin-top:.5rem;">Hand to cafeteria attendant on collection.</div>
    </div>`;
  },
  'homework-sheet'(p, f){
    return header(p) + `<h3 style="text-align:center;text-decoration:underline;">HOMEWORK / ASSIGNMENT</h3>
      <table style="width:100%;font-size:.9rem;margin:.5rem 0;"><tr><td><strong>Subject:</strong> ${esc(f.subject||'')}</td><td><strong>Class:</strong> ${esc(f.classLevel||'')}</td><td><strong>Teacher:</strong> ${esc(f.teacher||'')}</td></tr><tr><td><strong>Assigned:</strong> ${esc(f.assigned||'')}</td><td colspan="2"><strong>Due:</strong> ${esc(f.due||'')}</td></tr></table>
      <h4 style="margin-top:1rem;">${esc(f.title||'')}</h4>
      <div style="white-space:pre-wrap;line-height:1.7;border-left:4px solid ${p.primaryColor||'#1a2e4a'};padding-left:.8rem;">${esc(f.description||'')}</div>
      <p style="margin-top:2rem;font-size:.85rem;"><em>Parent's acknowledgement: _____________________________ Date: __________</em></p>
      ` + footer(p);
  },
});
